"""Initial schema: Corridor, TrainMovement, MaintenanceRequest, Block, Conflict, OptimizationRun, User

Revision ID: cb1f02153393
Revises: 
Create Date: 2026-09-23 18:15:18.668150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1f02153393'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('current_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridors_id'), 'corridors', ['id'], unique=False)
    op.create_index(op.f('ix_corridors_name'), 'corridors', ['name'], unique=True)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('availability_delta', sa.Float(), nullable=True),
    sa.Column('conflict_delta', sa.Float(), nullable=True),
    sa.Column('delay_risk_delta', sa.Float(), nullable=True),
    sa.Column('efficiency_delta', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('linked_work_orders', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_index(op.f('ix_blocks_track_id'), 'blocks', ['track_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_no', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_department'), 'maintenance_requests', ['department'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_track_id'), 'maintenance_requests', ['track_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_work_order_no'), 'maintenance_requests', ['work_order_no'], unique=True)
    op.create_table('train_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_no', sa.String(length=20), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_movements_corridor_id'), 'train_movements', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_train_movements_id'), 'train_movements', ['id'], unique=False)
    op.create_index(op.f('ix_train_movements_train_no'), 'train_movements', ['train_no'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_block_id'), 'conflicts', ['block_id'], unique=False)
    op.create_index(op.f('ix_conflicts_id'), 'conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_conflicts_track_id'), 'conflicts', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflicts_track_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_block_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_train_movements_train_no'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_corridor_id'), table_name='train_movements')
    op.drop_table('train_movements')
    op.drop_index(op.f('ix_maintenance_requests_work_order_no'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_track_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_department'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_blocks_track_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_corridors_name'), table_name='corridors')
    op.drop_index(op.f('ix_corridors_id'), table_name='corridors')
    op.drop_table('corridors')
    # ### end Alembic commands ###
